### ISSUE TITLE
Adapt to new access method

### ISSUE THREAD

**Issue by mlapp** [d-Rickyy-b/node-red-contrib-ffpass#4]
Ford has changed the login method for its API. Since then the contrib has been unusable and only receives the "401" in response to the request.

**Comment by d-Rickyy-b** [comment]
Hi and thanks for your comment. I am waiting for https://github.com/d4v3y0rk/ffpass-module/pull/12 to be merged.

**Comment by d-Rickyy-b** [comment]
Should be fixed in latest release https://github.com/d-Rickyy-b/node-red-contrib-ffpass/releases/tag/v0.1.5

See also https://github.com/d4v3y0rk/ffpass-module/releases/tag/v1.0.7
