### ISSUE TITLE
Still getting 401 and 429 errors

### ISSUE THREAD

**Issue by setpixel** [d-Rickyy-b/node-red-contrib-ffpass#5]
Hi!

I installed the node set directly from github for v 0.1.4. I'm still getting a 429 and 401 errors on status.

Am I doing anything wrong?

**Comment by d-Rickyy-b** [comment]
Hi there, thanks for creating an issue. Can you please provide some screenshots or copy the error messages into this issue? That way I can better check the issue. This issue should have been fixed upstream - at least nobody complained about it. https://github.com/d4v3y0rk/ffpass-module/issues/11#issuecomment-1012867950

How did you install the node set from github? Did you just import the source code as zip? I never actually tried that so I don't know if there might be issues related to that.

Also I just updated the version on the node-red website: https://flows.nodered.org/node/node-red-contrib-ffpass, maybe also try using that version.

**Comment by FightingNflder** [comment]
I'm seeing the same thing. Stopped working a few days ago. But the FordPass app still works.

**Comment by setpixel** [comment]
Yeah - I also left an issue on ffpass: https://github.com/d4v3y0rk/ffpass-module/issues/16

It appears that ford likes to change their api all the time and break stuff. Pretty crusty.

**Comment by mikje** [comment]
![image](https://user-images.githubusercontent.com/12999690/151203595-bd069a31-2e3d-48a4-8747-d6d303ab19b5.png)
![image](https://user-images.githubusercontent.com/12999690/151203641-a0b601f8-2b09-4cff-bc37-dc8f9e59da93.png)
Here are some screen shots regarding the 429 and 401 error which I have also
